version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ortomat
      POSTGRES_USER: ortomat_user
      POSTGRES_PASSWORD: secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data:
