name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: ortomat
          POSTGRES_USER: ortomat_user
          POSTGRES_PASSWORD: secure_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U ortomat_user -d ortomat"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint --if-present

      - name: Build Frontend
        run: cd apps/frontend && npm install && npm run build

      - name: Build Backend
        run: cd apps/backend && npm install && npm run build

      - name: Prisma check
        run: npx prisma validate
